# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('device_id', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=0)),
                ('pin_no', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
